import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        "primary-light": "var(--color-primary-light)",
        secondary: "var(--color-secondary)",
        "secondary-light": "var(--color-secondary-light)",
        accent: "var(--color-accent)",
        success: "var(--color-success)",
        "success-light": "var(--color-success-light)",
        warning: "var(--color-warning)",
        "warning-light": "var(--color-warning-light)",
        danger: "var(--color-danger)",
        "danger-light": "var(--color-danger-light)",
        "blue-money": "var(--color-blue-money)",
        "blue-money-light": "var(--color-blue-money-light)",
        "green-money": "var(--color-green-money)",
        "green-money-light": "var(--color-green-money-light)",
        okr: "var(--color-okr)",
        "okr-light": "var(--color-okr-light)",
        bg: "var(--color-bg)",
        surface: "var(--color-surface)",
        "surface-elevated": "var(--color-surface-elevated)",
        border: "var(--color-border)",
        "border-subtle": "var(--color-border-subtle)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-tertiary": "var(--color-text-tertiary)",
        "status-ok": "var(--status-ok)",
        "status-warning": "var(--status-warning)",
        "status-ko": "var(--status-ko)",
        "status-nodata": "var(--status-nodata)",
        "option-bg": "var(--color-option-bg)",
        backdrop: "var(--backdrop)",
        overlay: {
          subtle: "var(--overlay-subtle)",
          muted: "var(--overlay-muted)",
          hover: "var(--overlay-hover)",
          active: "var(--overlay-active)",
          border: "var(--overlay-border)",
          "border-hover": "var(--overlay-border-hover)",
        },
      },
      fontFamily: {
        sans: ['"Inter"', "system-ui", "-apple-system", "sans-serif"],
        display: ['"Inter"', "system-ui", "-apple-system", "sans-serif"],
        mono: ['"Inter"', "system-ui", "-apple-system", "sans-serif"],
      },
      boxShadow: {
        card: "var(--shadow-card)",
        "card-hover": "var(--shadow-card-hover)",
      },
      borderRadius: {
        card: "14px",
      },
      zIndex: {
        nav: "100",
        tooltip: "500",
        modal: "1000",
      },
    },
  },
  plugins: [],
} satisfies Config;
