"""add_budget_items_table

Revision ID: 0a36d381b6ca
Revises: f7c707c1e477
Create Date: 2026-03-12 10:28:14.341889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a36d381b6ca'
down_revision: Union[str, None] = 'f7c707c1e477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('managing_team', sa.String(length=100), nullable=False),
    sa.Column('concept', sa.Text(), nullable=False),
    sa.Column('expense_type', sa.String(length=50), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('capex_opex', sa.String(length=10), nullable=False),
    sa.Column('budget_area', sa.String(length=100), nullable=False),
    sa.Column('cost_center', sa.String(length=100), nullable=True),
    sa.Column('previous_year_budget', sa.Numeric(), nullable=True),
    sa.Column('previous_year_cost', sa.Numeric(), nullable=True),
    sa.Column('monthly_amount', sa.Numeric(), nullable=True),
    sa.Column('annual_amount', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('actual_amount', sa.Numeric(), nullable=True),
    sa.Column('invoice_reference', sa.String(length=200), nullable=True),
    sa.Column('order_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_items')
    # ### end Alembic commands ###
