"""add process documents and labels

Revision ID: 1a8c74d63a4d
Revises: e74175d68c44
Create Date: 2026-03-17 17:32:16.991099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8c74d63a4d'
down_revision: Union[str, None] = 'e74175d68c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'areas', 'members', ['responsable_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'departments', 'members', ['director_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'teams', 'members', ['coordinador_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'areas', type_='foreignkey')
    # ### end Alembic commands ###
