"""initial_tables

Revision ID: 8adb4d20fb77
Revises: 
Create Date: 2026-03-03 09:43:20.259581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adb4d20fb77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('target', sa.Numeric(), nullable=False),
    sa.Column('direction', sa.String(length=15), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('n8n_workflow_id', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_definitions_code'), 'kpi_definitions', ['code'], unique=True)
    op.create_table('n8n_sync_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('kpis_collected', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('okr_objectives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sponsor', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('budget_eur', sa.Numeric(), nullable=True),
    sa.Column('actual_cost_eur', sa.Numeric(), nullable=True),
    sa.Column('completion_pct', sa.Integer(), nullable=True),
    sa.Column('sponsor_satisfaction', sa.Numeric(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_table('kpi_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kpi_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collection_method', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpi_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kpi_id', 'year', 'month', name='uq_kpi_year_month')
    )
    op.create_table('okr_key_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('objective_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('baseline', sa.Numeric(), nullable=True),
    sa.Column('annual_target', sa.Numeric(), nullable=False),
    sa.Column('direction', sa.String(length=15), nullable=False),
    sa.Column('kpi_id', sa.Uuid(), nullable=True),
    sa.Column('kpi_aggregation', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpi_definitions.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['okr_objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('value_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('initiative', sa.String(length=200), nullable=False),
    sa.Column('hours_saved_annual', sa.Numeric(), nullable=True),
    sa.Column('hourly_rate_eur', sa.Numeric(), nullable=True),
    sa.Column('operational_savings_eur', sa.Numeric(), nullable=True),
    sa.Column('direct_savings_eur', sa.Numeric(), nullable=True),
    sa.Column('revenues_enabled_eur', sa.Numeric(), nullable=True),
    sa.Column('commercial_savings_eur', sa.Numeric(), nullable=True),
    sa.Column('it_attribution_pct', sa.Numeric(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('okr_quarterly_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_result_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('target', sa.Numeric(), nullable=True),
    sa.Column('actual', sa.Numeric(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['key_result_id'], ['okr_key_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_result_id', 'year', 'quarter', name='uq_kr_year_quarter')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('okr_quarterly_data')
    op.drop_table('value_items')
    op.drop_table('okr_key_results')
    op.drop_table('kpi_values')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('okr_objectives')
    op.drop_table('n8n_sync_logs')
    op.drop_index(op.f('ix_kpi_definitions_code'), table_name='kpi_definitions')
    op.drop_table('kpi_definitions')
    # ### end Alembic commands ###
