"""add_description_calc_method_year_assignments

Revision ID: c709ba5c5073
Revises: 8adb4d20fb77
Create Date: 2026-03-09 12:03:52.316891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c709ba5c5073'
down_revision: Union[str, None] = '8adb4d20fb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_year_assignments',
    sa.Column('kpi_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpi_definitions.id'], ),
    sa.PrimaryKeyConstraint('kpi_id', 'year')
    )
    op.add_column('kpi_definitions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('kpi_definitions', sa.Column('calculation_method', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi_definitions', 'calculation_method')
    op.drop_column('kpi_definitions', 'description')
    op.drop_table('kpi_year_assignments')
    # ### end Alembic commands ###
