"""add credentials connectors and kpi source type

Revision ID: f7c707c1e477
Revises: 7e6ce13785b8
Create Date: 2026-03-09 15:49:59.502099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7c707c1e477'
down_revision: Union[str, None] = '7e6ce13785b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('connectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('credential_id', sa.Uuid(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # Add source_type as nullable first, populate, then set NOT NULL
    op.add_column('kpi_definitions', sa.Column('source_type', sa.String(length=20), nullable=True))
    op.execute("UPDATE kpi_definitions SET source_type = 'manual' WHERE source_type IS NULL")
    op.alter_column('kpi_definitions', 'source_type', nullable=False, server_default='manual')
    op.add_column('kpi_definitions', sa.Column('connector_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'kpi_definitions', 'connectors', ['connector_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kpi_definitions', type_='foreignkey')
    op.drop_column('kpi_definitions', 'connector_id')
    op.drop_column('kpi_definitions', 'source_type')
    op.drop_table('connectors')
    op.drop_table('credentials')
    # ### end Alembic commands ###
